server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  server:
#    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
